openapi: 3.1.0
info:
  title: Syllabus_api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    parameters: []
  /user: {}
components:
  schemas:
    Course:
      title: Course
      type: object
      description: 'Classe course '
      properties:
        '':
          type: string
        teachers:
          type: array
          items: {}
        UE:
          type: string
        students:
          type: array
          items: {}
        academic_year:
          type: string
        syllabi:
          type: array
          items: {}
