openapi: 3.1.0
info:
  title: Syllabus_api
  version: '1.0'
  termsOfService: 'https://github.com/smarbal/syllabus-webservice.git'
servers:
  - url: 'https://api.ecam.be/syllabus-system'
paths:
  /course:
    get:
      summary: course
      tags: []
      responses: {}
      operationId: get-course
components:
  schemas:
    Course:
      title: Course
      type: object
      description: Course class
      properties:
        '':
          type: string
        teachers:
          type: array
          items: {}
        UE:
          type: string
        students:
          type: array
          items: {}
        academic_year:
          type: string
        syllabi:
          type: array
          items: {}
      examples:
        - '': string
          teachers:
            - null
          UE: string
          students:
            - null
          academic_year: string
          syllabi:
            - null
    Document:
      title: Document
      type: object
      description: Classe Document
      properties:
        name:
          type: string
        author:
          type: array
          items: {}
        publish_date:
          type: number
        pages:
          type: integer
    Order:
      title: Order
      type: object
      description: Classe Order
      properties:
        orderID:
          type: integer
        student: {}
        syllabi:
          type: array
          items: {}
        orderDate: {}
        price:
          type: number
        state:
          type: string
        '':
          type: string
    Student:
      title: Student
      type: object
      description: 'Classe Student extends User '
      properties:
        studentID:
          type: integer
        PAE:
          type: array
          items: {}
    Teacher:
      title: Teacher
      type: object
      description: Classe Teacher extends User
      properties:
        trigram:
          type: string
        courses:
          type: array
          items: {}
    User:
      title: User
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
