openapi: 3.1.0
info:
  title: Syllabus_api
  version: '1.0'
  termsOfService: 'https://github.com/smarbal/syllabus-webservice.git'
  description: ''
servers:
  - url: 'https://api.ecam.be/syllabus-webservice'
paths:
  '/Course/{name}':
    parameters:
      - schema:
          type: string
        name: name
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: Course Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
        '404':
          description: Not Found
      operationId: get-Course-CourseID
      description: Get Course Name
      parameters: []
    put:
      summary: ''
      operationId: put-Course-name
      responses:
        '202':
          description: Accepted
        '400':
          description: Bad Request
      description: Create New Or Edit Existing Course
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
    delete:
      summary: ''
      operationId: delete-Course-name
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
  '/Document/{name}':
    parameters:
      - schema:
          type: string
        name: name
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      operationId: get-Document-name
      parameters: []
      description: Get Document Name
      responses:
        '200':
          description: Document Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '404':
          description: Not Found
    put:
      summary: ''
      operationId: put-Document-name
      responses:
        '202':
          description: Accepted
        '400':
          description: Bad Request
      description: Create New Or Edit Existing Document
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
    delete:
      summary: ''
      operationId: delete-Document-name
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      description: Delete Document
  '/Order/{orderID}':
    parameters:
      - schema:
          type: string
        name: orderID
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: Order Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Not Found
      operationId: get-Order-orderID
      description: Get order ID
    put:
      summary: ''
      operationId: put-Order-orderID
      responses:
        '202':
          description: Accepted
        '400':
          description: Bad Request
      description: Create New Or Edit Existing Order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
    delete:
      summary: ''
      operationId: delete-Order-orderID
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      description: Delete Order
  '/User/{firstName}':
    parameters:
      - schema:
          type: string
        name: firstName
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Not Found
      operationId: get-User-firstName
      description: Get User FirstName
    put:
      summary: ''
      operationId: put-User-firstName
      responses:
        '202':
          description: Accepted
        '400':
          description: Bad Request
      description: Create New Or Edit Existing User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
    delete:
      summary: ''
      operationId: delete-User-firstName
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      description: Delete User
components:
  schemas:
    Course:
      title: Course
      type: object
      description: Course class
      examples:
        - name: string
          teachers:
            - null
          UE: string
          students:
            - null
          academic_year: string
          syllabi:
            - null
      properties:
        '':
          type: string
        teachers:
          type: array
          items: {}
        UE:
          type: string
        students:
          type: array
          items: {}
        academic_year:
          type: string
        syllabi:
          type: array
          items: {}
    Document:
      title: Document
      type: object
      description: Classe Document
      properties:
        name:
          type: string
        author:
          type: array
          items: {}
        publish_date:
          type: number
        pages:
          type: integer
    Order:
      title: Order
      type: object
      description: Classe Order
      properties:
        orderID:
          type: integer
        student: {}
        syllabi:
          type: array
          items: {}
        orderDate: {}
        price:
          type: number
        state:
          type: string
        '':
          type: string
    User:
      title: User
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
    Database:
      title: Database
      type: object
      description: Class Database
      properties:
        Connection:
          type: integer
